<?php

namespace Test;

use Luxury\Support\Facades\Log;

class EventTest extends \TestCase
{

    private $beforeDispatchLoop = false;

    private $beforeException = false;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->beforeDispatchLoop = false;
        $this->beforeException    = false;
    }

    public function testEventFired()
    {

        $em = $this->app->getEventsManager();

        $em->attach('dispatch:beforeDispatchLoop', function () {
            Log::debug(__METHOD__ . ':dispatch:beforeDispatchLoop');
            $this->beforeDispatchLoop = true;

            return true;
        });

        $em->attach('dispatch:beforeException', function () {
            Log::debug(__METHOD__ . ':dispatch:beforeException');
            $this->beforeException = true;

            return false;
        });

        $this->app->dispatcher->dispatch();

        $this->assertTrue($this->beforeDispatchLoop);
        $this->assertTrue($this->beforeException);
    }

    public function testAppEventFired()
    {

        $em = $this->app->getEventsManager();

        $em->attach('dispatch:beforeDispatchLoop', function () {
            Log::debug(__METHOD__ . ':dispatch:beforeDispatchLoop');
            $this->beforeDispatchLoop = true;

            return true;
        });

        $em->attach('dispatch:beforeException', function () {
            Log::debug(__METHOD__ . ':dispatch:beforeException');
            $this->beforeException = true;

            return false;
        });

        $this->app->handle('/phalcon-lust/');

        $this->assertTrue($this->beforeDispatchLoop);
        $this->assertFalse($this->beforeException);
    }
}