<?php

namespace App\Http\Controllers;

use Luxury\Middleware\Wtf as WtfMiddleware;
use Luxury\Support\Facades\Auth;

/**
 * Class AuthController
 *
 * @package     App\Http\Controllers
 */
class AuthController extends ControllerBase
{
    protected function onConstruct()
    {
        parent::onConstruct(); // TODO: Change the autogenerated stub

        $this->middleware(new WtfMiddleware());
    }

    public function signinAction()
    {
    }

    public function loginAction()
    {
        // Get the data from the user
        $email    = $this->request->getPost('email');
        $password = $this->request->getPost('password');

        $user = Auth::attempt([
            'email'    => $email,
            'password' => $password,
        ]);

        if (is_null($user)) {
            $this->flash->error('Wrong email/password');

            // Forward to the login form again
            $this->dispatcher->forward([
                'controller' => 'auth',
                'action'     => 'signin'
            ]);

            return;
        }

        $this->flash->success('Welcome ' . $user->name);

        // Forward to the 'invoices' controller if the user is valid
        $this->dispatcher->forward([
            'controller' => 'index',
            'action'     => 'index'
        ]);

        return;
    }
}